### ISSUE TITLE
sidebar vendor

### ISSUE THREAD

**Issue by moabi** [moabi/_o#13]
<pre>/mon-compte/edit-account/</pre> logged in as a vendor
* design avatar (using #user-account-widget)
* design vendor name (using #user-account-widget)
* design list with <code>fa</code> class (with #menu-vendor-account)

**Comment by moabi** [comment]
Dasboard vendor: 
changer l'ordre des tabs en css pour être conforme aux maquette : 

    ul.menu horizontal.black{
    display: flex;
    flex-direction: row;
    padding: 0;
    margin: 0;
    list-style: none;
    -ms-box-orient: horizontal;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -moz-flex;
    display: -webkit-flex;
    display: flex;
    -webkit-flex-flow: row wrap;
    flex-flow: row wrap;
    }

ul.menu horizontal.black li:nth-of-type(1) { order: 0; }
ul.menu horizontal.black li:nth-of-type(2) { order: 1; }
ul.menu horizontal.black li:nth-of-type(3) { order: 4; }
ul.menu horizontal.black li:nth-of-type(4) { order: 5; }
ul.menu horizontal.black li:nth-of-type(5) { order: 6; }
ul.menu horizontal.black li:nth-of-type(6) { order: 3; }

**Comment by julienrondeau** [comment]
ul.menu horizontal.black li:nth-of-type(4) est un item vide ....ça fout le bordel quand tu veux ordonner les items avec nth-of-type.... 
 pour le moment en display:none, mais il faudrait le killer dans le code
