### ISSUE TITLE
Page mon compte Vendor

### ISSUE THREAD

**Issue by julienrondeau** [moabi/_o#28]
d'après les maquettes Invisio, la sidebar est a gauche et ne reprend que les items "mon entreprise", "coordonnées bancaires" etc...  pas bloc "des questions"
..avec un avatar assez gros en haut de sidebar

check les maquettes Invisio pour voir la différence, si ce sont elles les référentes

**Comment by moabi** [comment]
j'ai fait une demande à Seb pour une réoganisation des maquettes
