### ISSUE TITLE
plugin de messagerie

### ISSUE THREAD

**Issue by julienrondeau** [moabi/_o#32]
comme je te disais, il y a beaucoup de <div> dans des <div> et le tout sans classe...
pas trop simple de cibler du coup...

bref j'ai fais sans pour le moment, ça évite de surcharger le template du plugin.
Tu me diras par rapport à ce que j'ai fais sur la messagerie si ça convient ou non

**Comment by moabi** [comment]
ok pour les classes de menu pure.css

**Comment by moabi** [comment]
TODO:
Messagerie ->
* faire des blocs de messages plus clairs sur : /dashboard/messagerie/?fepaction=viewmessage&id=1420 
s'inspirer de https://projects.invisionapp.com/share/794M312PT#/screens/173574846

**Comment by moabi** [comment]
@julienrondeau 
les messages imbriqués sont cachés sur : 
/dashboard/messagerie/?fepaction=viewmessage&id=1431
les montrer, virer le toggle sur le nom

**Comment by julienrondeau** [comment]
hello gars

je ne suis pas dispo de demain lundi à mercredi. je travaille sur un projet
qui était prévu à ces dates là.
Je serai en pointillé pour onlyoo car busy busy sauf urgence urgente :)

je réponds au téléphone si besoin.

++


*Julien Rondeau*http://www.julienrondeau.fr

Mob: +33.6.85.40.44.56

2016-09-23 18:40 GMT+02:00 David Fieffé <notifications@github.com>:
