### ISSUE TITLE
css pages

### ISSUE THREAD

**Issue by moabi** [moabi/_o#5]
@julienrondeau 

**while unlogged**

* .site-content-invite should not have a max 818px, instead use a wrapper to get the max width for both sidebar & main content; add a 1170px max width
* /mon-compte/ login & register form => two forms side to side
* forms : input[type=password] should be designed too
* forms : inputs should have a lower height (40px ?) - labels should get a font size related to it

**Once logged in as a vendor (momo)**

dashboard/product/edit/
* add a max width to the page
* /dashboard/order/ calendar goes behind the colophon

**Comment by julienrondeau** [comment]
ok j'ai mis un wrapper a max-width: 1170px;
avec pure-u-18-24 pour le contenu (.site-content-invite) et pure-u-6-24 pour la sidebar (#secondary.sidebar-account).
Dans la maquette, le contenu fait 870px de large et la sidebar 270px avec une marge de 30px entre les deux.
SI je ne leur mets pas de max-width ça ne fonctionne pas.... les blocs sont trop larges et la sidebar passe en bas.
Il doit y avoir une subtilité de Pure que je ne saisie pas....
