### ISSUE TITLE
page mon compte

### ISSUE THREAD

**Issue by julienrondeau** [moabi/_o#76]
il demande l'intégration de ces pages "mon compte".

- Sur la maquette il y a les sous-rubriques de "mon compte" dans la sidebar a gauche.
- La sidebar se trouve a gauche pour toutes les sous-partie de "mon compte" (avec le menu dedans)
- et surtout tout le design change par rapport aux autres parties de la dashboard (tout est sur fond gris etc...) 
il faudrait pouvoir avec une classe dans le body pour montrer que l'on est dans la partie "Mon compte" ainsi que dans ses sous- parties.

**Comment by moabi** [comment]
Validé avec Seb
